sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: Mwx4vdBvIlJrMRObkYx3WHjiKuneoSEx/7RwkrVzJ2Jf/VijBotPIAyZj+ouedCcF1QltaS5HTKW10mP26Xxgza2fbjiVtUFgQ2+6SACkT2zBaawkEvrwA5LpFgl8KJafrJeY0UVMSX4DuTsvN8Y33drbLzj9rd21O8pXiSYflW0Db1I57EakdDdE0gGR4Pkvk7Ohh5N1qzm7jGcnkRc2k6lW0ph84MxoIjenQecNaw5fl6WIcudUZ/2eiwbH11iKqdqsSONSNkzsYQjOQ+F/8aa6cgDgQmheZUgE8b2Qxlr6acRLaycTqTIlEBqt4wxFsVkjx2haULe2UdTBU5t+fXQXiCvOOagDPO1iatItVj5DMj2kDGyEi8HKFV1PF+S6TRInrd32sQr6Bda/f3D6arXNK+N9vHAsvapZciWrb+CcYhjo9liA7V4sGK9kEsmw0ys/Q68H0/wisQOD4a4aPT3W8tX5pI+ZnqsmqcIvVZLWJDh7PMbh790O8mdTc3khbygvx9PcxjmNndfQ3/DLlnyUaeU5QINqBYPkYWqE0FFzwRWmv+FhPnjEeRH1J5HMu0e0oLCj26Q6P+DZXTUeYTbn10bBxWBvJ6t2pxKe13CEqZPNfu7VKN6t1HqXhxkVoV/dXf9/BqSyXVbg8Vk3jrZucgKjY+YdP+WBNGA1Tw=
branches:
  only:
  - master
