# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'


# Website info
title: Andrew Miracle
description: Andrew is a Product Designer and Entrepreneur. My expertise is compassed from my years of experience in software development, Analytics and Technical Team Management.
cover: assets/images/blog-cover.jpg
logo: assets/images/blog-icon.png
logo_black: assets/images/am.png
logo_dark: assets/images/icon.png
favicon: assets/images/favicon.png
ref: assets/images/ref.png # fallback image for post content when there is no post cover
doing: EIT @MESTAfrica
doing_url: '#!'
reading: Rules of Management


# Social info
navigation: True # show the navbar links
subscribers: True # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: koolamusic # replace by your username
facebook: koolamusic # replace by your username
github: koolamusic
instagram: koolamusic
linkedin: salzzyandrewmiracle
medium: koolamusic

# Disqus
disqus: True
disqus_shortname: andrewmiracle-com # replace with your disqus username

# Jekyll Algolia Configuration
algolia:
  application_id: URCWH72LX4
  index_name: koolamusic
  search_only_api_key: 1586b65c714fbd834a502f35bfc0392c
  # files_to_exclude: []

# Google Analytics
google_analytics: UA-52368657-4 # replace with your GA tracking identifier

# Permalinks
permalink: posts/:title
# permalink: /:categories/:year/:month/:day/:title/
# permalink: /author/:author
# permalink: /tag/:tag

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jekyll-algolia]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: koolamusic
repo: bourbon
branch: master
destination: ../bourbon-pages/
production_url: https://andrewmiracle.com
CNAME: andrewmiracle.com #add cname for website to be created
source_url:  https://github.com/koolamusic/bourbon
relative_source: ../bourbon-pages
# source_url: https://andrewmiracle.com
# production_url:  https://andrewmiracle.com

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
